#!/usr/bin/env ruby
require 'pathname'
lib = Pathname.new(__FILE__).dirname + '..' + '..' + 'lib'
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require_relative 'config'

config = Config.new(
  toml: Pathname.new(__FILE__).dirname/'config.toml'
)

%w(blue green red purple yellow).each do |color|
  puts config.colors.send(color)
end
